---

image: python:3.10.4

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          script:
            - pip install -r requirements.txt
            - ls -la
            - python hello-world.py
            - echo "The code is okay"
      - step:
          name: Lint code
          script:
            - pip install -r requirements.txt
            - flake8 . --extend-exclude=dist,build --show-source --statistics
